numbers=[1,2,3,4,5]
print(numbers)
print(len(numbers))
numbers.append(6)
print(numbers)
numbers.insert(0,-1)
print(numbers)
numbers.remove(3)
print(numbers)
print(1 in numbers)
numbers.clear()
print(numbers)
